### ISSUE TITLE
Tell IDE to ignore files

### ISSUE THREAD

**Issue by pretzlaw** [editorconfig/specification#3]
Within projects there is a lot of generated (e.g. test output) or duplicated data (e.g. symlinks or after build process).
This leads to permanent reindex by the IDE for things we won't ever need to lookup.
Therefor IDEs can mark directories or files as "excluded" which should be a property in editorconfig too.

Notes:

* There could be multiple ways to mark a directory like ...
** Excluded (no index)
** Test Sources (index and special treatment)
** Source Root (index and major scope)
* We simply aim for a fully exclusion here
* the index won't be updated
* Searching for files, variables or classes won't show duplicate entries anymore.

**Comment by cxw42** [comment]
@pretzlaw That sounds like an interesting idea!  I am not an official site, but my understanding is that issues like this one belong in editorconfig/editorconfig instead of in this repo (per https://github.com/editorconfig/specification/issues/2#issuecomment-498430038).   May I suggest opening this issue there instead?  It will at least have more visibility there.

**Comment by pretzlaw** [comment]
Thanks @cxw42 . Now this also exists there.

**Comment by xuhdev** [comment]
Closing here
